owner: dicaire 
repo: status.dicaire.com 

assignees: bhdicaire
user-agent: bhdicaire

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

# notifications:
#   - type: slack
#     channel: 
    
status-website:
  name: Dicaire.com 
  cname: status.dicaire.com
  introMessage: This page shows **real-time** status of internet resources   
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
#  logoUrl: https://avatars0.githubusercontent.com/u/4814844?s=200&v=4
  logoHref: https://wakatime.com
  faviconSvg: https://wakatime.com/safari-pinned-tab.svg
  favicon: https://wakatime.com/favicon-32x32.png
  introTitle: Dicaire.com Status
  navbar:
    - title: Status
      href: /
    - title:Dicaire.com Home
      href: https://Dicaire.com
  customBodyHtml: "<script src="https://cdn.usefathom.com/script.js" data-site="BEWPUJUT" defer></script>"   
#   robotsText: "User-agent: * \n Disallow: /"
#     metaTags:
#       - name: "color-scheme"
#         content: "dark light"
#       - name: "robots"
#         content: "noindex"        
