owner: dicaire 
repo: status.dicaire.com 

assignees: bhdicaire
user-agent: bhdicaire

status-website:
  name: " " # dicaire.com status page
  cname: status.dicaire.com
  introTitle: "**Status page**"
  introMessage: "**Cloud providers:** [Apple](https://www.apple.com/support/systemstatus/), [AWS](https://health.aws.amazon.com/health/status), [Azure]( https://azure.status.microsoft/en-ca/status
), [Google Cloud](https://status.cloud.google.com/regional/americas), [Google Workspace](https://www.google.com/appsstatus/dashboard/), [MS](https://status.cloud.microsoft/), [MS 365](https://portal.office.com/adminportal/home?#/servicehealth), and [OVH](https://public-cloud.status-ovhcloud.com/)"
  logoUrl: https://raw.githubusercontent.com/dicaire/status.dicaire.com/main/assets/dicaire-logo.svg
  logoHref: https://Dicaire.com
  faviconSvg: https://raw.githubusercontent.com/dicaire/status.dicaire.com/main/assets/dicaire-icon.svg
  favicon: https://raw.githubusercontent.com/dicaire/status.dicaire.com/main/assets/dicaire-icon.png
  navbar:
    - title: Status
      href: /
    - title: Cloudflare
      href: https://www.cloudflarestatus.com/
    - title: GitHub
      href: https://www.githubstatus.com/
    - title: Zoom
      href: https://status.zoom.us/
  customBodyHtml: "<script src='https://cdn.usefathom.com/script.js' data-site='BEWPUJUT' defer></script>"
  themeUrl: https://status.dicaire.com/dcom.css

sites:
  - name: 'www.Dicaire.com'
    url: https://Dicaire.com
    icon: https://Dicaire.com/favicon.png
  - name: 'Sabrina.Dicaire.com'
    url: https://Sabrina.Dicaire.com
  - name: 'menu.Dicaire.com'
    url: https://menu.Dicaire.com
    icon: https://Dicaire.com/favicon.png
  - name: Mail Transport Agent Strict Transport Security (MTA-STS)
    url: https:/mta-sts.dicaire.com
    icon: https://Dicaire.com/favicon.png 
  - name: 'DNS – syeef.ns.Cloudflare.com'
    check: "tcp-ping"
    url: syeef.ns.cloudflare.com
    port: 53
    icon: https://www.cloudflare.com/favicon.ico
  - name: 'DNS – eve.ns.cloudflare.com'
    check: "tcp-ping"
    url: eve.ns.cloudflare.com
    port: 53
    icon: https://www.cloudflare.com/favicon.ico

# notifications:
#   - type: slack
#     channel: 
    
i18n:
  footer: ""
  activeIncidents: Active Incidents
  allSystemsOperational: All systems are operational
  incidentReport: "Incident #$NUMBER report →"
  activeIncidentSummary: Opened at $DATE with $POSTS posts
  incidentTitle: Incident $NUMBER Details
  incidentDetails: Incident Details
  incidentFixed: Fixed
  incidentOngoing: Ongoing
  incidentOpenedAt: Opened at
  incidentClosedAt: Closed at
  incidentViewOnGitHub: View and Subscribe on GitHub
  incidentCommentSummary: Posted at $DATE by $AUTHOR
  incidentBack: ← Back to all incidents
  pastIncidents: Past Incidents
  pastIncidentsResolved: Resolved in $MINUTES minutes with $POSTS posts
  liveStatus: Live Status
  overallUptime: "Overall uptime: $UPTIME"
  overallUptimeTitle: Overall uptime
  averageResponseTime: "Average response time: $TIMEms"
  averageResponseTimeTitle: Average response
  sevelDayResponseTime: 7-day response time
  responseTimeMs: Response time (ms)
  up: Up
  down: Down
  degraded: Degraded
  ms: ms
  loading: Loading
  navGitHub: GitHub
  rateLimitExceededTitle: Rate limit exceeded
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: An error occurred
  errorIntro: An error occurred in trying to get the latest status details.
  errorText: You can try again in a few moments.
  errorHome: Go to the homepage
  pastScheduledMaintenance: Past Scheduled Maintenance
  scheduledMaintenance: Scheduled Maintenance
  scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes
  scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes
  startedAt: Started at
  startsAt: Starts at
  duration: Duration
  durationMin: $DURATION minutes
  incidentCompleted: Completed
  incidentScheduled: Scheduled
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1y
  durationAll: all